language: python

python:
    - 3.5

sudo: false

env:
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py27-djmaster
    - TOX_ENV=py34-dj18
    - TOX_ENV=py34-dj19
    - TOX_ENV=py34-djmaster
    - TOX_ENV=py35-dj18
    - TOX_ENV=py35-dj19
    - TOX_ENV=py35-djmaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=py35-djmaster
    - env: TOX_ENV=py34-djmaster

install:
  - pip install "virtualenv<14.0.0" tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
